feat: qa migrations in pr

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -21,6 +21,46 @@ env:
   GITOPS_REPO_OUTPUTS_PATH: ./charts/apps/natsuite/values/.outputs
 
 jobs:
+  validate-flyway-migrations:
+    name: Validate Flyway Migrations
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Run PostgreSQL container
+        run: |
+          echo "Starting Crunchy PostgreSQL container..."
+          docker run -d --name postgres \
+            -e POSTGRES_USER=app-${{ github.event.number }} \
+            -e POSTGRES_PASSWORD=default \
+            -e POSTGRES_DB=app-${{ github.event.number }} \
+            -p 5432:5432 \
+            registry.developers.crunchydata.com/crunchydata/crunchy-postgres:16-3.4 \
+      - name: Create public schema
+        run: |
+          echo "Creating public schema and granting privileges..."
+          docker exec postgres psql -U app-${{ github.event.number }} -d app-${{ github.event.number }} -c "CREATE SCHEMA IF NOT EXISTS public;"
+          docker exec postgres psql -U app-${{ github.event.number }} -d app-${{ github.event.number }} -c "GRANT ALL PRIVILEGES ON SCHEMA public TO \"app-${{ github.event.number }}\";"
+
+      - name: Install Flyway
+        run: |
+          echo "Installing Flyway CLI version 10..."
+          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10/flyway-commandline-10-linux-x64.tar.gz | tar xvz
+          sudo ln -s $(pwd)/flyway-10/flyway /usr/local/bin/flyway
+
+      - name: Run Flyway migrations
+        run: |
+          echo "Running Flyway migrations..."
+          flyway info migrate -outOfOrder=true \
+            -url=jdbc:postgresql://localhost:5432/app-${{ github.event.number }} \
+            -user=app-${{ github.event.number }} \
+            -password=default \
+            -baselineOnMigrate=true \
+            -defaultSchema=public \
+            -locations=filesystem:./migrations/migrations,filesystem:./migrations/test-only-migrations \
+            && echo "Flyway migrations completed successfully" || echo "Flyway migrations failed"
+        continue-on-error: true
+
   # https://github.com/bcgov/action-builder-ghcr
   builds:
     name: Builds
@@ -50,7 +90,7 @@ jobs:
   # https://github.com/bcgov/quickstart-openshift
   crunchy:
     name: Deploy Crunchy
-    needs: [builds]
+    needs: [builds, validate-flyway-migrations]
     uses: ./.github/workflows/.dbdeployer.yml
     with:
       s3_enabled: false # no backups in dev
