chore: Fix and check for valid vars and secrets (#975)

diff --git a/.github/workflows/pr-version-bump.yml b/.github/workflows/pr-version-bump.yml
--- a/.github/workflows/pr-version-bump.yml
+++ b/.github/workflows/pr-version-bump.yml
@@ -16,11 +16,25 @@ jobs:
       actions: "read"
     if: github.event.pull_request.merged == true
     steps:
+      - name: Validate Inputs
+        if: steps.triggers.outputs.triggered == 'true'
+        shell: bash
+        run: |
+          echo "Checking for mandatory inputs"
+          if [ ! "${{ vars.TEAM_WOLVERINE_GITHUB_APP_ID }}" ]; then
+            echo "Variable TEAM_WOLVERINE_GITHUB_APP_ID not found"
+            exit 1
+          fi
+          if [ ! "${{ vars.TEAM_WOLVERINE_GITHUB_APP_PRIVATE_KEY }}" ]; then
+            echo "Variable TEAM_WOLVERINE_GITHUB_APP_PRIVATE_KEY not found"
+            exit 1
+          fi
+
       - uses: actions/create-github-app-token@v1
         id: app-token
         with:
-          app-id: ${{ vars.VERSION_BUMPER_APPID }}
-          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}
+          app-id: ${{ vars.TEAM_WOLVERINE_GITHUB_APP_ID }}
+          private-key: ${{ secrets.TEAM_WOLVERINE_GITHUB_APP_PRIVATE_KEY }}
 
       - uses: actions/checkout@v4
         with:
